services:
  blogsite.wasm:
    image: blogsite.wasm
    build:
      context: .
      dockerfile: BlogSite.Wasm/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    expose:
      - '80'
      - '443'
    depends_on: 
      - blogsite.api
  blogsite.api:
    image: blogsite.api
    build:
      context: .
      dockerfile: BlogSite.Api/Dockerfile
    environment:
      DB_HOST: blogsite.db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - '5000:80'
      - '5001:443'
    expose:
      - '5000'
      - '5001'
    depends_on:
      - blogsite.db
  blogsite.db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - blogsite-db-volume:/var/lib/mysql
volumes:
  blogsite-db-volume:    