services:
  blogsite.wasm:
    image: "ghcr.io/lechuckthepirate/blogsite-wasm:latest"
    ports:
      - '80:80'
      - '443:443'
    expose:
      - '80'
      - '443'
  blogsite.api:
    image: "ghcr.io/lechuckthepirate/blogsite-api:latest"
    environment:
      DB_HOST: blogsite.db
      DB_PORT: 3306
      DB_USER: {{ secrets.DB_USER }}}
      DB_PASSWORD: {{ secrets.DB_PASSWORD }}
    ports:
      - '5000:80'
      - '5001:443'
    expose:
      - '80'
      - '443'
  blogsite.db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: {{ secrets.DB_USER }}
      MYSQL_PASSWORD: {{ secrets.DB_PASSWORD }}
      MYSQL_ROOT_PASSWORD: {{ secrets.DB_PASSWORD }}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - blogsite-db-volume:/var/lib/mysql
volumes:
  blogsite-db-volume:    
