services:
  blogsite.wasm:
    image: ghcr.io/lechuckthepirate/blogsite-wasm:latest
    ports:
      - '80:80'
      - '443:443'
    expose:
      - '80'
      - '443'
    volumes:
      - /etc/letsencrypt/live/4998b9d.online-server.cloud/privkey.pem:/root/ssl/key.pem
      - /etc/letsencrypt/live/4998b9d.online-server.cloud/cert.pem:/root/ssl/cert.pem
  blogsite.api:
    image: ghcr.io/lechuckthepirate/blogsite-api:latest
    environment:
      DB_HOST: blogsite.db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5000:80'
      - '5001:443'
    expose:
      - '5000'
      - '5001'
    depends_on:
      - blogsite.db
  blogsite.db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-volume:/var/lib/mysql
        
volumes:
  db-volume:    
